### ISSUE TITLE
How to write nested If using this ? Is this feature avalaible yet ?

### ISSUE THREAD

**Issue by GurpreetSingh5** [anantab/serverless-plugin-ifelse#8] opened 2019-05-27 12:49 UTC
How to write nested If using this? Is this feature available yet?
I want to check multiple nested conditions?

**Comment by anantab** [comment] 2019-05-28 05:11
> How to write nested If using this? Is this feature available yet?
> I want to check multiple nested conditions?

You can easily achieve nested conditions by writing multiple if conditions. Eg
```
- If: '"${self:custom.currentStage}" == "dev"'
        Set:
          provider.profile: dev
- If: '"${self:custom.currentStage}" == "test"'
        Set:
          provider.profile: test
- If: '"${self:custom.currentStage}" != "dev" && ${self:custom.currentStage}" != "test"'
        Set:
          provider.profile: prod

```

**Comment by anantab** [comment] 2019-05-28 08:00
Duplicate of [#5](https://github.com/anantab/serverless-plugin-ifelse/issues/5)

**Closed as completed by anantab** 2019-05-28 08:00 UTC
